---
gracefulShutdownTimeout: 30
apns:
  concurrentWorkers: 100
  connectionPoolSize: 10
  logStatsInterval: 10000
  apps: "game"
  certs:
    game:
      authKeyPath: /certs/authkey.p8
      keyID: "ABC123DEFG"
      teamID: "ABC123DEFG"
      topic: "com.game.test"
gcm:
  pingInterval: 30
  pingTimeout: 10
  maxPendingMessages: 100
  logStatsInterval: 10000
  apps: "game"
  certs:
    game:
      apiKey: game-api-key
      senderID: "1233456789"
queue:
  topics:
    - "^push-[^-_]+_(apns|gcm)[_-](single|massive)"
  brokers: "localhost:9941"
  group: testGroup
  sessionTimeout: 6000
  offsetResetStrategy: latest
  handleAllMessagesBeforeExiting: true
  channelSize: 100
feedback:
  reporters:
    - kafka
  kafka:
    topics: "push-test_apns-feedbacks"
    brokers: "localhost:9941"
  cache:
    requestTimeout: 1800000
    cleaningInterval: 300000
stats:
  reporters:
    - statsd
  statsd:
    host: "localhost:8125"
    prefix: "push"
    buflen: 1
invalidToken:
  pg:
    table: "test_apns"
    host: localhost
    port: 8585
    user: pusher_user
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: push
    connectionTimeout: 100
    chanSize: 1000
